/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteRouteImport } from './routes/_protected/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DebugIndexRouteImport } from './routes/debug/index'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as ProtectedDashboardRouteImport } from './routes/_protected/dashboard'
import { Route as ProtectedIamUsersIndexRouteImport } from './routes/_protected/iam/users/index'
import { Route as ProtectedIamRolesIndexRouteImport } from './routes/_protected/iam/roles/index'
import { Route as ProtectedIamDepartmentsIndexRouteImport } from './routes/_protected/iam/departments/index'

const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugIndexRoute = DebugIndexRouteImport.update({
  id: '/debug/',
  path: '/debug/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedIamUsersIndexRoute = ProtectedIamUsersIndexRouteImport.update({
  id: '/iam/users/',
  path: '/iam/users/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedIamRolesIndexRoute = ProtectedIamRolesIndexRouteImport.update({
  id: '/iam/roles/',
  path: '/iam/roles/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedIamDepartmentsIndexRoute =
  ProtectedIamDepartmentsIndexRouteImport.update({
    id: '/iam/departments/',
    path: '/iam/departments/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/debug/': typeof DebugIndexRoute
  '/iam/departments/': typeof ProtectedIamDepartmentsIndexRoute
  '/iam/roles/': typeof ProtectedIamRolesIndexRoute
  '/iam/users/': typeof ProtectedIamUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/debug': typeof DebugIndexRoute
  '/iam/departments': typeof ProtectedIamDepartmentsIndexRoute
  '/iam/roles': typeof ProtectedIamRolesIndexRoute
  '/iam/users': typeof ProtectedIamUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/_protected/dashboard': typeof ProtectedDashboardRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/debug/': typeof DebugIndexRoute
  '/_protected/iam/departments/': typeof ProtectedIamDepartmentsIndexRoute
  '/_protected/iam/roles/': typeof ProtectedIamRolesIndexRoute
  '/_protected/iam/users/': typeof ProtectedIamUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/auth/login'
    | '/auth/register'
    | '/debug/'
    | '/iam/departments/'
    | '/iam/roles/'
    | '/iam/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/auth/login'
    | '/auth/register'
    | '/debug'
    | '/iam/departments'
    | '/iam/roles'
    | '/iam/users'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/_protected/dashboard'
    | '/auth/login'
    | '/auth/register'
    | '/debug/'
    | '/_protected/iam/departments/'
    | '/_protected/iam/roles/'
    | '/_protected/iam/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  DebugIndexRoute: typeof DebugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug/': {
      id: '/debug/'
      path: '/debug'
      fullPath: '/debug/'
      preLoaderRoute: typeof DebugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/iam/users/': {
      id: '/_protected/iam/users/'
      path: '/iam/users'
      fullPath: '/iam/users/'
      preLoaderRoute: typeof ProtectedIamUsersIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/iam/roles/': {
      id: '/_protected/iam/roles/'
      path: '/iam/roles'
      fullPath: '/iam/roles/'
      preLoaderRoute: typeof ProtectedIamRolesIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/iam/departments/': {
      id: '/_protected/iam/departments/'
      path: '/iam/departments'
      fullPath: '/iam/departments/'
      preLoaderRoute: typeof ProtectedIamDepartmentsIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
  }
}

interface ProtectedRouteRouteChildren {
  ProtectedDashboardRoute: typeof ProtectedDashboardRoute
  ProtectedIamDepartmentsIndexRoute: typeof ProtectedIamDepartmentsIndexRoute
  ProtectedIamRolesIndexRoute: typeof ProtectedIamRolesIndexRoute
  ProtectedIamUsersIndexRoute: typeof ProtectedIamUsersIndexRoute
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedDashboardRoute: ProtectedDashboardRoute,
  ProtectedIamDepartmentsIndexRoute: ProtectedIamDepartmentsIndexRoute,
  ProtectedIamRolesIndexRoute: ProtectedIamRolesIndexRoute,
  ProtectedIamUsersIndexRoute: ProtectedIamUsersIndexRoute,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  DebugIndexRoute: DebugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
